### ISSUE TITLE
Баллы в зависимости от заполнения репозитория

### ISSUE THREAD

**Issue by markpolyak** [markpolyak/lab-grader#4]
Реализовать возможность изменения коэффициента, на который умножаются баллы за лабораторную работу (см. issue https://github.com/markpolyak/lab-grader/issues/3), в зависимости от наполнения репозитория студентом. 

Например:
- в конфиге (сейчас это settings.py) указано, что репозиторий для конкретной ЛР должен содержать не менее трех коммитов студента и этот пункт задания на ЛР "стоит" 15% рейтинга; (для справки: если указанный в конфиге максимальный рейтинг за ЛР равен 8 баллам, то студент может получить 8*0,15=1,2 балла просто за три любых коммита, код при этом проверяется преподавателем отдельно); соответственно, если условие выполнено, то в гугл-таблицу записывается `?v*0.15`, а если не выполнено, то не записывается ничего; знак вопрос в начале строки нужен, чтобы рейтинг студента обновился при последующей проверке, если студент за прошедшее время выполнит еще какие-то требования задания;
- в конфиге указано, что репозиторий для конкретной ЛР должен содержать не менее трех issues, каждой из которых соответствует коммит студента; скрипт проверяет наличие открытых и закрытых issues, удовлетворяющих условиям, и если их не меньше необходимого количества - добавляет к коэффициенту рейтинга заданное число %%; например, если три issues "стоят" 20% рейтинга, то при выполнении также условия из предыдущего примера мы получим запись `?v*0.35`, а при выполнении только данного условия - `?v*0.2`.

Итогом должна быть возможность через конфиг, описывающий лабораторную работу, задать дополнительные требования на заполнение репозитория, за которые студенты смогут получить (или потерять) рейтинг.

**Comment by markpolyak** [comment]
Информация о количестве коммитов и issues берется из GitHub API.

**Comment by markpolyak** [comment]
Сейчас эти условия прописаны в заданиях на ЛР 5 и 6 по ОС, см. https://github.com/k43guap/os-course-task5

**Comment by nphl** [comment]
TODO: Сделать проверку issues на наличие связанных с ними коммитов через [GitHub Issue Events](https://developer.github.com/v3/issues/events/) и засчитывать баллы только в случае соблюдения количества issues и при наличии в них коммитов

Также отдельно коммиты проверять только по количеству (и "префиксу", который должен просто присутствовать в commit message в 6 лабе) и за это отдельные баллы
